stages:
  - lint
  - test
  - race-test
  - build
  - integration-test
  - package

image: golang:1.22

variables:
  GOMODCACHE: "$CI_PROJECT_DIR/.cache/go/pkg/mod"
  GOCACHE: "$CI_PROJECT_DIR/.cache/go-build"

cache:
  key: "$CI_JOB_NAME"
  paths:
    - .cache/go/pkg/mod
    - .cache/go-build

lint:
  stage: lint
  script:
    - go vet ./...

golangci:
  stage: lint
  image: golangci/golangci-lint:v1.56
  script:
    - golangci-lint run --timeout=5m

unit-test:
  stage: test
  script:
    - go test ./...

race-test:
  stage: race-test
  script:
    - go test -race ./...

integration-test:
  stage: integration-test
  script:
    - go test -v ./tests

build:
  stage: build
  script:
    - go build ./cmd/arbitrage

package-image:
  stage: package
  image: docker:25.0.3
  services:
    - docker:25.0.3-dind
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - docker build -t arbitr:ci .

