# golangci-lint configuration
# Minimal config compatible with golangci-lint v1.62.0

run:
  timeout: 5m

linters:
  enable:
    - govet 
    - ineffassign
    - unused
  disable-all: true

issues:
  exclude-use-default: true
  exclude-dirs:
    - vendor
