# This file contains the configuration for golangci-lint
# See https://golangci-lint.run/usage/configuration/ for more details

version: 2

run:
  timeout: 5m
  go: "1.22"
  skip-dirs:
    - vendor

linters:
  # Enable only basic linters for CI stability
  enable:
    - govet 
    - ineffassign
    - unused
  disable-all: true

linters-settings:
  govet:
    disable:
      - fieldalignment  # too noisy
      - shadow         # can be noisy
      - unusedresult   # can be noisy

issues:
  exclude-use-default: true
  exclude-dirs:
    - vendor
    - tests  # exclude test directory
  max-issues-per-linter: 50
  max-same-issues: 3
