network:
  region: EU-West
  ws_keepalive_seconds: 15
logging:
  level: info
  pretty: false
server:
  addr: ":9090"
  pprof: false
  read_timeout_seconds: 5
  write_timeout_seconds: 10
  idle_timeout_seconds: 60
  admin_allow_cidrs:
    - 127.0.0.0/8
    - ::1/128

trading:
  enabled: false
  pairs: [BTCUSDT, ETHUSDT, BNBUSDT, SOLUSDT, XRPUSDT, ADAUSDT, DOGEUSDT, LTCUSDT, TRXUSDT, MATICUSDT, DOTUSDT, LINKUSDT]
  min_net_bps: 5
  notional_usd: 100
  fees_bps:
    bybit: 10
  slippage_bps: 1
  risk_reserve_bps: 0.5
  # Triangles must be valid markets on Bybit spot. Below are commonly liquid examples; adjust to real availability on Bybit.
  triangles:
    - { AB: BTCUSDT, BC: ETHUSDT,   CA: ETHBTC }
    - { AB: BTCUSDT, BC: BNBUSDT,   CA: BNBBTC }
    - { AB: BTCUSDT, BC: SOLUSDT,   CA: SOLBTC }
    - { AB: BTCUSDT, BC: XRPUSDT,   CA: XRPBTC }
    - { AB: BTCUSDT, BC: ADAUSDT,   CA: ADABTC }
    - { AB: BTCUSDT, BC: DOGEUSDT,  CA: DOGEBTC }
    - { AB: BTCUSDT, BC: LTCUSDT,   CA: LTCBTC }
    - { AB: BTCUSDT, BC: TRXUSDT,   CA: TRXBTC }
    - { AB: BTCUSDT, BC: MATICUSDT, CA: MATICBTC }
    - { AB: BTCUSDT, BC: DOTUSDT,   CA: DOTBTC }
    - { AB: BTCUSDT, BC: LINKUSDT,  CA: LINKBTC }
